import { Language } from './types';

export const TRANSLATIONS = {
  fr: {
    appTitle: "ToJbs",
    dashboard: "Tableau de Bord",
    invoices: "Factures Fournisseurs",
    vendors: "Fournisseurs",
    clients: "Factures Clients",
    bankStatements: "Relevés Bancaires",
    planComptable: "Plan Comptable",
    usersManagement: "Utilisateurs",
    upload: "Importer",
    settings: "Paramètres",
    logout: "Déconnexion",
    loginTitle: "Accès Sécurisé",
    loginSubtitle: "Veuillez vous authentifier pour accéder aux données financières.",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    loginBtn: "Connexion",
    totalSpent: "Total Dépensé (TTC)",
    totalHT: "Total HT",
    totalTVA: "Total TVA",
    invoiceCount: "Nombre de Factures",
    uploadTitle: "Déposer vos fichiers ici",
    uploadSubtitle: "Supporte PDF, JPG, PNG et Scans. Importez plusieurs documents à la fois.",
    processing: "Traitement en cours...",
    exportExcel: "Journal Achats",
    exportSales: "Journal Ventes",
    exportBank: "Journal Banque",
    saveWork: "Sauvegarder",
    clearAll: "Tout effacer",
    tableDate: "Date",
    tableVendor: "Fournisseur",
    tableClient: "Client",
    tableICE: "ICE",
    tableHT: "Montant HT",
    tableTTC: "Montant TTC",
    tableTVA: "Taux TVA",
    tableActions: "Actions",
    noData: "Aucune donnée disponible",
    search: "Rechercher...",
    welcome: "Bienvenue",
    copyright: "Développé par SLIMANE CHAGRI",
    tvaDistribution: "Répartition TVA",
    recentActivity: "Activité Récente",
    securityCheck: "Vérification de sécurité...",
    accessGranted: "Accès autorisé",
    language: "Langue",
    importBtn: "Importer",
    addInvoice: "Nouvelle Facture",
    sectionPurchases: "Achats (Dépenses)",
    sectionSales: "Ventes (Revenus)",
    totalPurchasesTTC: "Total Achats TTC",
    totalPurchasesHT: "Total Achats HT",
    totalPurchasesTVA: "Total TVA Achats",
    totalSalesTTC: "Total Ventes TTC",
    totalSalesHT: "Total Ventes HT",
    totalSalesTVA: "Total TVA Ventes",
    topVendor: "Top Fournisseur",
    topClient: "Top Client",
    pcmTitle: "Plan Comptable Marocain",
    pcmSubtitle: "Référence rapide des principaux comptes",
    role: "Rôle",
    status: "Statut",
    lastLogin: "Dernière connexion",
    addUser: "Ajouter utilisateur",
    edit: "Modifier",
    delete: "Supprimer",
    confirmDelete: "Êtes-vous sûr de vouloir supprimer cet utilisateur ?",
    editUserPrompt: "Entrez le nouveau nom de l'utilisateur :",
    enterUserName: "Nom du nouvel utilisateur :",
    or: "Ou",
    loginGoogle: "Continuer avec Google",
    emailLabel: "Email",
    view: "Consulter"
  },
  ar: {
    appTitle: "ToJbs",
    dashboard: "لوحة التحكم",
    invoices: "فواتير الموردين",
    vendors: "الموردين",
    clients: "فواتير العملاء",
    bankStatements: "كشوف الحسابات",
    planComptable: "دليل الحسابات",
    usersManagement: "المستخدمين",
    upload: "تحميل",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    loginTitle: "دخول آمن",
    loginSubtitle: "الرجاء تسجيل الدخول للوصول إلى البيانات المالية.",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    loginBtn: "دخول",
    totalSpent: "إجمالي المصاريف (TTC)",
    totalHT: "إجمالي HT",
    totalTVA: "إجمالي الضريبة",
    invoiceCount: "عدد الفواتير",
    uploadTitle: "أفلت الملفات هنا",
    uploadSubtitle: "يدعم PDF, JPG, PNG والمسح الضوئي. يمكنك رفع ملفات متعددة.",
    processing: "جارِ المعالجة...",
    exportExcel: "دفتر المشتريات",
    exportSales: "دفتر المبيعات",
    exportBank: "دفتر البنك",
    saveWork: "حفظ العمل",
    clearAll: "مسح الكل",
    tableDate: "التاريخ",
    tableVendor: "المورد",
    tableClient: "العميل",
    tableICE: "ICE",
    tableHT: "المبلغ HT",
    tableTTC: "المبلغ TTC",
    tableTVA: "نسبة الضريبة",
    tableActions: "إجراءات",
    noData: "لا توجد بيانات",
    search: "بحث...",
    welcome: "مرحباً",
    copyright: "تطوير سليمان شغري",
    tvaDistribution: "توزيع الضريبة",
    recentActivity: "النشاط الأخير",
    securityCheck: "تدقيق أمني...",
    accessGranted: "تم السماح بالدخول",
    language: "اللغة",
    importBtn: "استيراد",
    addInvoice: "فاتورة جديدة",
    sectionPurchases: "المشتريات",
    sectionSales: "المبيعات",
    totalPurchasesTTC: "اجمالي المشتريات TTC",
    totalPurchasesHT: "اجمالي المشتريات HT",
    totalPurchasesTVA: "اجمالي الضريبة على المشتريات",
    totalSalesTTC: "اجمالي المبيعات TTC",
    totalSalesHT: "اجمالي المبيعات HT",
    totalSalesTVA: "اجمالي الضريبة على المبيعات",
    topVendor: "أهم الموردين",
    topClient: "أهم العملاء",
    pcmTitle: "التصميم المحاسبي المغربي",
    pcmSubtitle: "مرجع سريع للحسابات الرئيسية",
    role: "الدور",
    status: "الحالة",
    lastLogin: "آخر ظهور",
    addUser: "إضافة مستخدم",
    edit: "تعديل",
    delete: "حذف",
    confirmDelete: "هل أنت متأكد أنك تريد حذف هذا المستخدم؟",
    editUserPrompt: "أدخل الاسم الجديد للمستخدم:",
    enterUserName: "اسم المستخدم الجديد:",
    or: "أو",
    loginGoogle: "المتابعة باستخدام Google",
    emailLabel: "البريد الإلكتروني",
    view: "عرض"
  }
};